SELECT EMP_ID, EMP_NAME ,EMP_NO ,EMAIL ,PHONE,
NVL(DEPT_TITLE, '부서없음') DEPT_TITLE , JOB_NAME,SALARY 
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON(DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;

SELECT 	emp_name
FROM EMPLOYEE;


UPDATE EMPLOYEE SET EMAIL = '?' WHERE EMP_ID = ?
UPDATE EMPLOYEE SET PHONE = '?' WHERE EMP_ID = ?
UPDATE EMPLOYEE SET SALARY = '?' WHERE EMP_ID = ?

DELETE FROM EMPLOYEE WHERE EMP_ID;
