--1번
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY STUDENT_NAME;

--1번(2)


--2번
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
ORDER BY STUDENT_SSN DESC;

--3번 
SELECT STUDENT_NAME 학생이름,STUDENT_NO 학번,STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%'
AND (STUDENT_ADDRESS LIKE '강원%' OR STUDENT_ADDRESS LIKE '경기%')
ORDER BY STUDENT_NAME; 

--4번
SELECT PROFESSOR_NAME, PROFESSOR_SSN  
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY PROFESSOR_SSN;

--5번
SELECT STUDENT_NO, POINT
FROM TB_GRADE 
WHERE TERM_NO = '200402'
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

--6번
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME 
FROM TB_STUDENT S, TB_DEPARTMENT D
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
ORDER BY STUDENT_NO;

--7번 
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_DEPARTMENT D, TB_CLASS C
WHERE D.DEPARTMENT_NO = C.DEPARTMENT_NO; 

--8번
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS C,TB_CLASS_PROFESSOR CP,TB_PROFESSOR P
WHERE C.CLASS_NO  = CP.CLASS_NO
AND CP.PROFESSOR_NO = P.PROFESSOR_NO;

--9번
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS C,TB_CLASS_PROFESSOR CP,TB_PROFESSOR P,TB_DEPARTMENT D
WHERE C.CLASS_NO  = CP.CLASS_NO
AND CP.PROFESSOR_NO = P.PROFESSOR_NO
AND C.DEPARTMENT_NO = D.DEPARTMENT_NO
AND CATEGORY = '인문사회';

--10번
SELECT S.STUDENT_NO 학번,STUDENT_NAME 학생이름,ROUND(AVG(POINT),1)
FROM TB_STUDENT S,TB_GRADE G,TB_DEPARTMENT D
WHERE S.STUDENT_NO = G.STUDENT_NO
AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND D.DEPARTMENT_NO = '059'
GROUP BY S.STUDENT_NO,STUDENT_NAME
ORDER BY S.STUDENT_NO;


--11번
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT D, TB_STUDENT S, TB_PROFESSOR P
WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO
AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO  
AND STUDENT_NO = 'A313047';

--11번(풀이)
SELECT DEPARTMENT_NAME 학과이름, 
STUDENT_NAME 학생이름,
PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--(2)
SELECT DEPARTMENT_NAME 학과이름, 
STUDENT_NAME 학생이름,
PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S
JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';




--12번
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT S, TB_GRADE G,TB_CLASS C 
WHERE S.STUDENT_NO = G.STUDENT_NO
AND G.CLASS_NO = C.CLASS_NO 
AND TERM_NO LIKE '2007%'
AND CLASS_NAME = '인간관계론';

--12번(풀이)
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론'
AND TERM_NO LIKE '2007%';



--13번
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C, TB_DEPARTMENT D,TB_CLASS_PROFESSOR CP
WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO 
AND C.CLASS_NO = CP.CLASS_NO(+)
AND CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;

--13번(풀이)
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS 
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;



--14번
SELECT STUDENT_NAME 학생이름,NVL(PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT S, TB_PROFESSOR P,TB_DEPARTMENT D
WHERE S.COACH_PROFESSOR_NO = P.PROFESSOR_NO(+)
AND D.DEPARTMENT_NO = S.DEPARTMENT_NO
AND DEPARTMENT_NAME = '서반아어학과';

--14번(풀이)
SELECT STUDENT_NAME 학생이름,NVL(PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;



--15번
SELECT S.STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT S, TB_DEPARTMENT D, TB_GRADE G
WHERE S.DEPARTMENT_NO = D.DEPARTMENT_NO
AND S.STUDENT_NO = G.STUDENT_NO
AND ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0;

--15번(풀이)
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름",
TRUNC(AVG(POINT),8) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N' --휴학생이 아닌 사람
GROUP BY STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;




--16번
SELECT C.CLASS_NO, C.CLASS_NAME, AVG(POINT)
FROM TB_CLASS C, TB_GRADE G,TB_DEPARTMENT D
WHERE C.CLASS_NO = G.CLASS_NO 
AND C.DEPARTMENT_NO = D.DEPARTMENT_NO 
AND DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY C.CLASS_NO, C.CLASS_NAME;

--16번(풀이)
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8) "AVG(POINT)"
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO,CLASS_NAME
ORDER BY 1;

























