--1번
SELECT EMP_ID, EMP_NAME,PHONE,HIRE_DATE,DEPT_TITLE
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE (DEPT_CODE) = (SELECT DEPT_CODE
                              FROM EMPLOYEE
                              WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연'; 

--2번
SELECT EMP_NAME,SALARY,HIRE_DATE
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM HIRE_DATE ) > 2000; --2000년도 이후 사원 급여

SELECT EMP_ID,EMP_NAME,PHONE,SALARY,JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE SALARY = (SELECT MAX(SALARY)
                     FROM EMPLOYEE
                     WHERE EXTRACT(YEAR FROM HIRE_DATE ) > 2000); 

--3번
SELECT DEPT_CODE,JOB_CODE,EMP_NAME 
FROM EMPLOYEE
WHERE EMP_NAME = '노옹철'; --D9	J2 노옹철

SELECT EMP_ID,EMP_NAME,DEPT_CODE,JOB_CODE,DEPT_TITLE,JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE (DEPT_CODE,JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
                              FROM EMPLOYEE
                              WHERE EMP_NAME = '노옹철')
AND EMP_NAME != '노옹철'; 

--4번
SELECT EMP_ID,EMP_NAME,DEPT_CODE,JOB_CODE 
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM HIRE_DATE ) = 2000;  --2000년도에 입사한 사원 --204	유재식	D6	J3

SELECT EMP_ID,EMP_NAME,DEPT_CODE,JOB_CODE,HIRE_DATE
FROM EMPLOYEE
WHERE (DEPT_CODE,JOB_CODE) = (SELECT DEPT_CODE,JOB_CODE 
                              FROM EMPLOYEE
                              WHERE EXTRACT(YEAR FROM HIRE_DATE ) = 2000);

--5번
SELECT EMP_ID,EMP_NAME,DEPT_CODE,MANAGER_ID,EMP_NO,HIRE_DATE 
FROM EMPLOYEE
WHERE (DEPT_CODE,MANAGER_ID) = (SELECT DEPT_CODE,MANAGER_ID
                                 FROM EMPLOYEE
                                 WHERE SUBSTR(EMP_NO,8,1)='2'
                                 AND SUBSTR(EMP_NO,1,2)='77');
                                
--6번
SELECT EMP_ID,EMP_NAME,NVL(DEPT_TITLE,'소속없음'),JOB_NAME,HIRE_DATE  
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE HIRE_DATE IN (SELECT MIN(HIRE_DATE)
                   FROM EMPLOYEE 
                   WHERE ENT_YN = 'N'
                   GROUP BY DEPT_CODE )
ORDER BY HIRE_DATE;


--7번
SELECT EMP_ID,EMP_NAME,JOB_NAME,나이,보너스포함연봉
FROM 
(SELECT EMP_ID,EMP_NAME,JOB_NAME,TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), (19 || SUBSTR(EMP_NO,1,6))) /12) 나이,
(SALARY * (NVL(BONUS,0) + 1)) *12 보너스포함연봉
FROM EMPLOYEE
NATURAL JOIN JOB)
WHERE 나이 IN (SELECT MIN(TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), (19 || SUBSTR(EMP_NO,1,6))) /12))
              FROM EMPLOYEE
              GROUP BY JOB_CODE)
               
ORDER BY 나이 DESC;








