--카테고리
CREATE TABLE CATEGORIES (
CATEGORY_ID NUMBER PRIMARY KEY,
CATEGORY_NAME VARCHAR2(100) UNIQUE
);

COMMENT ON COLUMN CATEGORIES.CATEGORY_ID IS '카테고리 ID';
COMMENT ON COLUMN CATEGORIES.CATEGORY_NAME IS '카테고리 이름';

SELECT * FROM CATEGORIES;

--상품정보
CREATE TABLE PRODUCTS (
	PRODUCT_ID NUMBER PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(100) NOT NULL,
	PRICE NUMBER DEFAULT 0,
	STOCK_QUANTITY NUMBER DEFAULT 0,
	CATEGORY NUMBER ,
	CONSTRAINT FK_CATEGORIES FOREIGN KEY (CATEGORY)
	REFERENCES CATEGORIES(CATEGORY_ID)
);

--고객정보

--주문 정보

--주문상세정보