--게시글 목록조회
SELECT BOARD_NO, BOARD_TITLE ,MEMBER_NM,CREATE_DT ,READ_COUNT,
(SELECT COUNT(*) FROM "COMMENT" SUB 
 WHERE SUB.BOARD_NO = MAIN.BOARD_NO
 AND DELETE_FL = 'N') COMMENT_COUNT
FROM "BOARD" MAIN
JOIN "MEMBER" USING(MEMBER_NO)
WHERE DELETE_FL = 'N'
ORDER BY BOARD_NO DESC;