CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(100)		NOT NULL,
	"MEMBER_NICKNAME" VARCHAR2(30) NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호(SEQ_MEMBER_NO)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 이름(별명)';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(N:탈퇴X, Y: 탈퇴O)';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);
-- 탈퇴여부 CHECK 제약 조건
ALTER TABLE "MEMBER" ADD CONSTRAINT "CH_MEMBER_DEL_FL" 
CHECK("MEMBER_DEL_FL" IN ('N', 'Y'));


-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- 샘플 계정 추가
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'frog01', 'pass01'
	, '개굴', DEFAULT, DEFAULT);

-- 샘플 계정 추가
INSERT INTO "MEMBER"
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'frog02', 'pass02'
	, '개굴이', DEFAULT, DEFAULT);


CREATE TABLE "RECORD" (
	"RECORD_NO" NUMBER NOT NULL,
	"RECORD_TITLE" VARCHAR2(300) NOT NULL,
	"RECORD_MEMO" VARCHAR2(500),
	"RECORD_DATE" DATE	DEFAULT SYSDATE NOT NULL,
	"RECORD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO" NUMBER NOT NULL
);

COMMENT ON COLUMN "RECORD"."RECORD_NO" IS '일기번호(SEQ_TODO_NO)';

COMMENT ON COLUMN "RECORD"."RECORD_TITLE" IS '일기 제목';

COMMENT ON COLUMN "RECORD"."RECORD_MEMO" IS '일기 내용';

COMMENT ON COLUMN "RECORD"."RECORD_DATE" IS '작성날짜';

COMMENT ON COLUMN "RECORD"."RECORD_DEL_FL" IS '삭제 여부(N : 삭제X , Y : 삭제O)';

COMMENT ON COLUMN "RECORD"."RECORD_NO" IS '작성자 회원 번호';

-- 시퀀스 생성
CREATE SEQUENCE SEQ_TODO_NO NOCACHE;

ALTER TABLE "TODO" ADD CONSTRAINT "PK_TODO" PRIMARY KEY (
	"TODO_NO"
);

ALTER TABLE "TODO" ADD CONSTRAINT "FK_MEMBER_TO_TODO" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

-- 샘플 투두 추가
INSERT INTO "TODO"
VALUES(SEQ_TODO_NO.NEXTVAL, '모르는 개 산책', '?뭐지'
	, DEFAULT, DEFAULT, 1);

COMMIT;