--1번
SELECT DEPARTMENT_NAME "학과 명",CATEGORY 계열 
FROM TB_DEPARTMENT;
--2번
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명입니다' AS "학과별 정원"
FROM TB_DEPARTMENT;
--3번
SELECT STUDENT_NAME
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT  
WHERE DEPARTMENT_NAME = '국어국문학과'
AND SUBSTR(STUDENT_SSN,8,1)= '2'
AND ABSENCE_YN = 'Y';
--4번
SELECT STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079','A513090','A513091','A513110','A513119')
ORDER BY STUDENT_NO DESC;
--5번
SELECT DEPARTMENT_NAME,CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30; 