/* 연습문제
SYS (관리자계정)
계정 'exam_이니셜' 로 생성 후 해당 계정에서 진행.


테이블명 : MAJOR
1. MAJOR_NO (학과번호) : NUMBER - PK
2. MAJOR_NM (학과명) : VARCHAR2(100) - NOT NULL




테이블명 : STUDENT
1. STUDENT_ID (학번) : NUMBER - PK
2. STUDENT_NAME (이름) : VARCHAR2(20) - NOT NULL
3. GENDER (성별) : VARCHAR2(3) CHECK ('남' , '여')
4. BIRTH (생년월일 : 'YYYY-MM-DD '형식으로 작성) : DATE
5. MAJOR_NO (전공학과번호) : NUMBER - FK (부모키 삭제 시 자식키 NULL 로 변경)



각 테이블마다 INSERT 5개 이상,
MAJOR_NM 학과명 MAJOR_NAME으로 변경해보기 

*/

CREATE TABLE MAJOR (
	MAJOR_NO NUMBER CONSTRAINT PK_MAJOR PRIMARY KEY,
	MAJOR_NM VARCHAR2(100) CONSTRAINT NN_MAJOR_NM NOT NULL
);

COMMENT ON COLUMN MAJOR.MAJOR_NO  IS '학과번호';
COMMENT ON COLUMN MAJOR.MAJOR_NM  IS '학과명';

INSERT INTO MAJOR 
VALUES('001','국어국문학과');

INSERT INTO MAJOR 
VALUES('002','수학과');

INSERT INTO MAJOR 
VALUES('003','실용음악과');

INSERT INTO MAJOR 
VALUES('004','시각미디어디자인과');

INSERT INTO MAJOR 
VALUES('005','철학과');

SELECT * FROM MAJOR;

ALTER TABLE MAJOR RENAME COLUMN MAJOR_NM TO MAJOR_NAME;



CREATE TABLE STUDENT(
	STUDENT_ID NUMBER CONSTRAINT PK_STUDENT_ID PRIMARY KEY,
	STUDENT_NAME VARCHAR2(20) CONSTRAINT NN_STUDENT_NAME NOT NULL,
	GENDER VARCHAR2(3) CONSTRAINT CK_GENDER CHECK(GENDER IN ('남','여')),
	BIRTH DATE,
	MAJOR_NO NUMBER CONSTRAINT NN_MAJOR_NO , 
	ABSENCE VARCHAR2(3) DEFAULT 'N' CONSTRAINT NN_ABSENCE NOT NULL,
	CONSTRAINT CK_ABSENCE CHECK(ABSENCE IN ('Y','N'))
);

COMMENT ON COLUMN STUDENT.STUDENT_ID IS '학번';
COMMENT ON COLUMN STUDENT.STUDENT_NAME  IS '이름';
COMMENT ON COLUMN STUDENT.GENDER  IS '성별';
COMMENT ON COLUMN STUDENT.BIRTH  IS '생년월일';
COMMENT ON COLUMN STUDENT.ABSENCE  IS '휴학여부';
COMMENT ON COLUMN STUDENT.MAJOR_NO  IS '전공학과번호';

INSERT INTO STUDENT
VALUES('19273641','황상철','남','19870213','001','N');
INSERT INTO STUDENT
VALUES('28234221','김윤아','여','19900127','002','N');
INSERT INTO STUDENT
VALUES('19273644','장윤주','여','19920421','003','N');
INSERT INTO STUDENT
VALUES('18233642','유재석','남','19770318','004','N');
INSERT INTO STUDENT
VALUES('29273650','조승우','남','19930427','005','Y');

SELECT * FROM STUDENT;

ALTER TABLE STUDENT ADD CONSTRAINT FK_MAJOR_NO FOREIGN KEY (MAJOR_NO) REFERENCES MAJOR(MAJOR_NO);

UPDATE STUDENT SET STUDENT_ID = 19273641
WHERE STUDENT_NAME = '황상철';

UPDATE STUDENT SET STUDENT_ID = 28234221
WHERE STUDENT_NAME = '김윤아';

UPDATE STUDENT SET STUDENT_ID = 19273644
WHERE STUDENT_NAME = '장윤주';

UPDATE STUDENT SET STUDENT_ID = 18233642
WHERE STUDENT_NAME = '유재석';

UPDATE STUDENT SET STUDENT_ID = 29273650
WHERE STUDENT_NAME = '조승우';

COMMIT;

































